---
- name: set the name of the bucket
  set_fact: s3_bucket="{{ stack_name }}-openshift-docker-registry-{{ ansible_date_time.epoch }}"
- name: Create S3 bucket
  s3:
    bucket: "{{ s3_bucket }}"
    mode: create
    region: "{{ region }}"
