---
- name: Install the required rpms
  yum: name={{ item }} state=latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - python-httplib2
  when: deployment_type == "openshift-enterprise"
- name: Install the required rpms
  dnf: name={{ item }} state=latest
  with_items:
      - wget
      - git
      - net-tools
      - bind-utils
      - iptables-services
      - bridge-utils
      - bash-completion
      - docker
      - python-httplib2
  when: ansible_distribution == "Fedora"
