- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
      - vars/main.yaml
  vars:
    vpc_subnet_azs: "{{ lookup('ec2_zones_by_region', region) }}"
  roles:
      - pre-install-check 
      - cloudformation-infra
