- hosts: localhost
  connection: local
  gather_facts: yes
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      # Group systems
      - cfn-outputs
      - instance-groups

- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars_files:
      - vars/main.yaml
  roles:
      - host-up

- include: ../../common/playbooks/prerequisite.yaml

- include: openshift-setup.yaml
