AWSTemplateFormatVersion: '2010-09-09'
Description: OpenShift Cluster Template
Parameters:
  NamePrefix:
    Type: String
    Default: openshift_
  MasterApiPort:
    Type: Number
    Default: 443


  VpcId:
    Type: String
  VpcTemplateUrl:
    Type: String
    Default: 'https://s3.amazonaws.com/openshift-cloudformation-templates/vpc/vpc.yaml'
  NumSubnets:
    Type: Number
    MinValue: 1
    MaxValue: 4
    Default: 1
  SubnetAvailabilityZones:
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  SubnetCidrBlocks:
    Type: CommaDelimitedList
    Default: '172.18.0.0/24,172.18.1.0/24,172.18.2.0/24,172.18.3.0/24'
  VpcCidrBlock:
    Type: String
    Default: 172.18.0.0/16


  MasterExtElbSecurityGroups:
    Type: CommaDelimitedList
  MasterIntElbSecurityGroups:
    Type: CommaDelimitedList
  RouterElbSecurityGroups:
    Type: CommaDelimitedList
  MasterSecurityGroups:
    Type: CommaDelimitedList
  EtcdSecurityGroups:
    Type: CommaDelimitedList
  NodeSecurityGroups:
    Type: CommaDelimitedList
  RouterSecurityGroups:
    Type: CommaDelimitedList
  MasterSecurityGroups:
    Type: CommaDelimitedList
  SecurityGroupTemplateUrl:
    Type: String
    Default: 'https://s3.amazonaws.com/openshift-cloudformation-templates/security-groups/default.yaml'


  MasterInstanceProfile:
    Type: String
  NodeInstanceProfile:
    Type: String
  IamInstanceProfileTemplateUrl:
    Type: String
    Default: 'https://s3.amazonaws.com/openshift-cloudformation-templates/iam-policy/iam.yaml'


Conditions:
  CreateVpc:
    'Fn::Equals':
    - ''
    - Ref: VpcId
  CreateSecurityGroups:
    'Fn::Or':
    - 'Fn::Equals':
      - ''
      - 'Fn::Join':
        - ','
        - Ref: MasterSecurityGroups
    - 'Fn::Equals':
      - ''
      - 'Fn::Join':
        - ','
        - Ref: NodeSecurityGroups
  CreateIAMProfiles:
    'Fn::Or':
    - 'Fn::Equals':
      - ''
      - Ref: MasterInstanceProfile
    - 'Fn::Equals':
      - ''
      - Ref: NodeInstanceProfile

Resources:
  VpcStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateVpc
    Properties:
      TemplateURL:
        Ref: VpcTemplateUrl
      Parameters:
        VpcName:
          'Fn::Join':
          - ''
          - - Ref: NamePrefix
            - _vpc
        NumSubnets:
          Ref: NumSubnets
        SubnetAvailabilityZones:
          'Fn::Join':
          - ','
          - Ref: SubnetAvailabilityZones
        SubnetCidrBlocks:
          'Fn::Join':
          - ','
          - Ref: SubnetCidrBlocks
        VpcCidrBlock:
          Ref: VpcCidrBlock
  SGStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateSecurityGroups
    Properties:
      TemplateURL:
        Ref: SecurityGroupTemplateUrl
      Parameters:
        VpcId:
          'Fn::If':
          - CreateVpc
          - 'Fn::GetAtt':
            - VpcStack
            - Outputs.VpcId
          - Ref: VpcId
        MasterApiPort:
          Ref: MasterApiPort

  IAMStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateIAMProfiles
    Properties:
      TemplateURL:
        Ref: IamInstanceProfileTemplateUrl

