AWSTemplateFormatVersion: '2010-09-09'
Description: OpenShift Cluster Template
Parameters:
  NamePrefix:
    Type: String
    Default: openshift_
  VpcId:
    Type: String
  VpcTemplateUrl:
    Type: String
    Default: 'https://s3.amazonaws.com/openshift-cloudformation-templates/vpc.yaml'
  NumSubnets:
    Type: Number
    MinValue: 1
    MaxValue: 4
    Default: 1
  SubnetAvailabilityZones:
    Type: 'List<AWS::EC2::AvailabilityZone::Name>'
  SubnetCidrBlocks:
    Type: CommaDelimitedList
    Default: '172.18.0.0/24,172.18.1.0/24,172.18.2.0/24,172.18.3.0/24'
  VpcCidrBlock:
    Type: String
    Default: 172.18.0.0/16
Conditions:
  CreateVpc:
    'Fn::Equals':
    - ''
    - Ref: VpcId
Resources:
  VpcStack:
    Type: 'AWS::CloudFormation::Stack'
    Condition: CreateVpc
    Properties:
      TemplateURL:
        Ref: VpcTemplateUrl
      Parameters:
        VpcName:
          'Fn::Join':
          - ''
          - - Ref: NamePrefix
            - _vpc
        NumSubnets:
          Ref: NumSubnets
        SubnetAvailabilityZones:
          'Fn::Join':
          - ','
          - Ref: SubnetAvailabilityZones
        SubnetCidrBlocks:
          'Fn::Join':
          - ','
          - Ref: SubnetCidrBlocks
        VpcCidrBlock:
          Ref: VpcCidrBlock
