---
- name: Gather facts
  openshift_facts:
    role: common

- name: Set Origin fact
  set_fact:
    openshift_release: "{{ origin_release }}"
  when: deployment_type == "origin"

- block:
  - name: Clear yum cache
    command: "yum clean all"
    ignore_errors: true

  - name: Install the required rpms
    package:
      name: "{{ item }}"
      state: latest
    with_items: "{{ openshift_required_packages }}"

  - name: Start NetworkManager and network
    service:
      name: "{{ item }}"
      state: restarted
      enabled: true
    with_items:
    - NetworkManager
    - network

  - name: Determine if firewalld is installed
    rpm_q:
      name: "firewalld"
      state: present
    register: firewalld_installed
    failed_when: false

  - name: Stop firewalld
    service:
      name: firewalld
      state: stopped
      enabled: false
    when:
    - "{{ firewalld_installed.installed_versions | default([]) | length > 0 }}"

  - name: Start iptables
    service:
      name: iptables
      state: started
      enabled: true

  when: not openshift.common.is_atomic | bool

# Fail as early as possible if Atomic and old version of Docker
- block:

  # See https://access.redhat.com/articles/2317361
  # and https://github.com/ansible/ansible/issues/15892
  # NOTE: the "'s can not be removed at this level else the docker command will fail
  # NOTE: When ansible >2.2.1.x is used this can be updated per
  # https://github.com/openshift/openshift-ansible/pull/3475#discussion_r103525121
  - name: Determine Atomic Host Docker Version
    shell: 'CURLY="{"; docker version --format "$CURLY{json .Server.Version}}"'
    register: l_atomic_docker_version

  - assert:
      msg: Installation on Atomic Host requires Docker 1.12 or later. Please upgrade and restart the Atomic Host.
      that:
      - l_atomic_docker_version.stdout | replace('"', '') | version_compare('1.12','>=')

  when: l_is_atomic | bool

