---
- name: Clear yum cache
  command: "yum clean all"
  ignore_errors: true

- name: Install the required rpms
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ openshift_required_packages }}"

- name: Start NetworkManager and network
  service:
    name: "{{ item }}"
    state: restarted
    enabled: true
  with_items:
  - NetworkManager
  - network

- name: Start iptables
  service:
    name: iptables
    state: started
    enabled: true

- name: Start docker
  service:
    name: docker
    state: started
    enabled: true
