---
- name: Gather facts
  openshift_facts:
    role: common

- block:
  - name: Determine if excluder packages are installed
    rpm_q:
      name: "{{ openshift.common.service_type }}-excluder"
      state: present
    failed_when: false
    register: openshift_excluder_installed

  - name: Exclude atomic-openshift packages
    command: {{ openshift.common.service_type }}-excluder exclude
    when:
    - "{{ openshift_excluder_installed.installed_versions | default([]) | length > 0 }}"


  - name: Exclude docker package
    command: {{ openshift.common.service_type }}-excluder exclude
    when:
    - "{{ openshift_excluder_installed.installed_versions | default([]) | length > 0 }}"

  when: not openshift.common.is_atomic | bool
