---
- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  roles:
  - role: rhel_subscribe
    when: deployment_type in ["enterprise", "atomic-enterprise", "openshift-enterprise"] and
          ansible_distribution == "RedHat" and rhel_subscription_user is defined
  - { role: rhsm-subscription, when rhel_subscription_user is not defined and rhel_subscription_pass is not defined and rhel_subscription_pool is not defined }

- hosts: cluster_hosts
  gather_facts: no
  become: yes
  roles:
  - { role: rhsm-repos, when rhel_subscription_user is not defined and rhel_subscription_pass is not defined and rhel_subscription_pool is not defined }
  - prerequisites

- hosts: master
  gather_facts: yes
  become: yes
  roles:
  - master-prerequisites
