---
- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  roles:
  - rhsm-timeout
  - role: atomic-update
    when: openshift.common.is_atomic

- hosts: cluster_hosts
  gather_facts: no
  become: yes
  roles:
  - rhsm-repos
  - prerequisites

- hosts: master
  gather_facts: yes
  become: yes
  roles:
  - master-prerequisites
