---
- hosts: cluster_hosts
  gather_facts: yes
  become: yes
  serial: 1
  roles:
      - ../roles/rhsm-subscription

- hosts: cluster_hosts
  gather_facts: no
  become: yes
  roles:
      - ../roles/rhsm-repos
      - ../roles/prerequisites
